# Generated by Django 5.2.3 on 2025-06-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto', models.CharField(help_text='Ex: Ração, Suplemento, Brinquedo, etc.', max_length=100, verbose_name='Tipo do Produto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade em estoque', verbose_name='Quantidade')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em quilogramas', max_digits=10, verbose_name='Peso (kg)')),
                ('fornecedor', models.CharField(max_length=150, verbose_name='Fornecedor')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço unitário em reais', max_digits=10, verbose_name='Preço (R$)')),
                ('data_compra', models.DateField(verbose_name='Data da Compra')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o produto', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
