# Generated by Django 5.2.3 on 2025-07-03 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='motivo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('AJUSTE', 'Ajuste de estoque'), ('PERDA', 'Perda/Descarte'), ('DEVOLUCAO', 'Devolução'), ('OUTRO', 'Outro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='product',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tipo_produto',
            field=models.CharField(max_length=100, verbose_name='Tipo do Produto'),
        ),
        migrations.CreateModel(
            name='AlertaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTOQUE_BAIXO', 'Estoque Baixo'), ('PROXIMO_VENCIMENTO', 'Próximo do Vencimento'), ('PRODUTO_SEM_MOVIMENTACAO', 'Produto sem Movimentação')], max_length=50)),
                ('mensagem', models.TextField()),
                ('nivel', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], max_length=20)),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque',
                'verbose_name_plural': 'Alertas de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data_validade', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='products.product')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['data_validade'],
            },
        ),
    ]
